# Generated by Django 3.2.3 on 2021-06-07 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('university', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('credit', models.IntegerField(default=4)),
                ('instructor', models.CharField(max_length=255)),
                ('bubble', models.CharField(choices=[('Circles', 'Circles'), ('Squares', 'Squares')], max_length=100)),
                ('questions', models.IntegerField(default=50)),
                ('choices', models.IntegerField(default=4)),
                ('choiceLabels', models.CharField(choices=[('A-B-C', 'A-B-C'), ('i-ii-iii', 'i-ii-iii'), ('1-2-3', '1-2-3')], max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
