# Generated by Django 3.2.3 on 2021-06-11 09:57

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_quiz_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='remarks',
            field=django_mysql.models.ListTextField(models.CharField(max_length=255), default=['courage'], max_length=100, size=None),
        ),
    ]
