# Generated by Django 3.2.3 on 2021-06-13 10:14

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_quiz_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.nameFile)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='api.quiz')),
            ],
        ),
    ]
