# Generated by Django 3.2.3 on 2021-07-15 13:19

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='failMark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='marksDistribution',
            field=django_mysql.models.ListCharField(models.CharField(max_length=3), default=['2'], max_length=255, size=None),
        ),
        migrations.AddField(
            model_name='quiz',
            name='sheet_name',
            field=models.CharField(default='default_sheet', max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='correctAnswers',
            field=django_mysql.models.ListCharField(models.CharField(max_length=3), default=['1'], max_length=255, size=None),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='marksAllocation',
            field=django_mysql.models.ListCharField(models.CharField(max_length=3), default=['2'], max_length=255, size=None),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.IntegerField(default=10),
        ),
    ]
