# Generated by Django 3.2.3 on 2021-07-15 13:39

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210715_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='remarks',
            field=django_mysql.models.ListTextField(models.CharField(blank=True, default='', max_length=255, null=True), default=['courage'], size=None),
        ),
    ]
