# Generated by Django 3.2.3 on 2021-07-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_quiz_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('corrected', 'corrected')], default='pending', max_length=50),
        ),
    ]
