# Generated by Django 3.2.3 on 2021-07-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_image_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='SheetImage',
        ),
    ]
