# Generated by Django 3.2.3 on 2021-07-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_image_sheetimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetimage',
            name='url',
            field=models.CharField(default='url', max_length=255),
            preserve_default=False,
        ),
    ]
