# Generated by Django 3.2.3 on 2021-07-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_sheetimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='corrected_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='pending_images',
            field=models.IntegerField(default=0),
        ),
    ]
