# Generated by Django 3.2.3 on 2021-07-20 12:15

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210717_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='marksDistribution',
            field=django_mysql.models.ListTextField(models.CharField(blank=True, default='', max_length=255, null=True), default=['2'], size=None),
        ),
    ]
