# Generated by Django 3.2.3 on 2021-09-02 15:23

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_quiz_marksdistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_number', models.IntegerField(default=1)),
                ('correct_ans', django_mysql.models.ListCharField(models.CharField(default='', max_length=255), max_length=255, size=None)),
                ('wrong_ans', django_mysql.models.ListCharField(models.CharField(default='', max_length=255), max_length=255, size=None)),
                ('mark_distribution', django_mysql.models.ListCharField(models.CharField(blank=True, default='', max_length=100, null=True), max_length=255, size=None)),
                ('total_mark', models.DecimalField(decimal_places=2, max_digits=3)),
                ('remark', models.TextField()),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='api.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='api.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_correct', django_mysql.models.ListCharField(models.CharField(default='', max_length=100), max_length=255, size=None)),
                ('answered_wrong', django_mysql.models.ListCharField(models.CharField(default='', max_length=100), max_length=255, size=None)),
                ('percentage_pass', models.DecimalField(decimal_places=2, max_digits=3)),
                ('mark', models.DecimalField(decimal_places=2, max_digits=3)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
