# Generated by Django 3.2.3 on 2021-09-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210902_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='correctAnswers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='marksAllocation',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='marksDistribution',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='remarks',
        ),
    ]
