# Generated by Django 3.2.3 on 2021-09-02 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210902_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='sheet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='api.quiz'),
        ),
    ]
