# Generated by Django 3.2.3 on 2021-09-10 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_student_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sheet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.quiz'),
        ),
    ]
